# application.properties의
# server.port=9000와 
# server.servlet.context-path=/boot06를
# application.yml로 작성하면
server:
  port: 9000
  servlet:
    context-path: /boot6

# application.properties의
# spring.mvc.view.prefix=/WEB-INF/views/와
# spring.mvc.view.suffix=.jsp를
# application.yml로 작성하면
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp